// <auto-generated />
using System;
using System.Collections.Generic;
using IMDB.API.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMDB.API.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.NameBasic", b =>
                {
                    b.Property<string>("NConst")
                        .HasColumnType("text");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("KnownForTitles")
                        .HasColumnType("text[]");

                    b.Property<string>("PrimaryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PrimaryProfessions")
                        .HasColumnType("text[]");

                    b.HasKey("NConst");

                    b.HasIndex("PrimaryName")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PrimaryName"), "GIN");

                    b.ToTable("NameBasics");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitleAka", b =>
                {
                    b.Property<string>("TitleId")
                        .HasColumnType("text");

                    b.Property<int>("Ordering")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Attributes")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsOriginalTitle")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Types")
                        .HasColumnType("text[]");

                    b.HasKey("TitleId", "Ordering", "Title");

                    b.ToTable("TitleAkas");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitleBasic", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("RuntimeMinutes")
                        .HasColumnType("bigint");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TConst");

                    b.HasIndex("PrimaryTitle", "OriginalTitle")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PrimaryTitle", "OriginalTitle"), "GIN");

                    b.ToTable("TitleBasics");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitleCrew", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Directors")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Writers")
                        .HasColumnType("text[]");

                    b.HasKey("TConst");

                    b.ToTable("TitleCrews");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitleEpisode", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ParentTConst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer");

                    b.HasKey("TConst");

                    b.ToTable("TitleEpisodes");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitlePrincipal", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.Property<int>("Ordering")
                        .HasColumnType("integer");

                    b.Property<string>("NConst")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character")
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.HasKey("TConst", "Ordering", "NConst");

                    b.ToTable("TitlePrincipals");
                });

            modelBuilder.Entity("IMDB.API.ApiService.Data.Models.TitleRating", b =>
                {
                    b.Property<string>("TConst")
                        .HasColumnType("text");

                    b.Property<float>("AverageWeighting")
                        .HasColumnType("real");

                    b.Property<int>("NumVotes")
                        .HasColumnType("integer");

                    b.HasKey("TConst");

                    b.ToTable("TitleRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
